-- Every date-time column stores a point in time with its time zone. The old
-- columns (timestamp without time zone) hold UTC: Prisma writes UTC, and the
-- database defaults were written in UTC (the session time zone of
-- production is UTC; the rows of the midnight jobs are at 22:00 and 23:00,
-- which is 00:00 in Europe/Berlin). Thus each value is read as UTC.
-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "AuditEvent" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "BlueprintUnlock" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Citizen" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "birthdayGreetingSentAt" SET DATA TYPE TIMESTAMPTZ(3) USING "birthdayGreetingSentAt" AT TIME ZONE 'UTC',
ALTER COLUMN "newYearGreetingSentAt" SET DATA TYPE TIMESTAMPTZ(3) USING "newYearGreetingSentAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "CitizenAppFavorite" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "CitizenLog" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "confirmedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "confirmedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "DailyLoginCount" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EmailConfirmationToken" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMPTZ(3) USING "expires" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "endTime" SET DATA TYPE TIMESTAMPTZ(3) USING "endTime" AT TIME ZONE 'UTC',
ALTER COLUMN "startTime" SET DATA TYPE TIMESTAMPTZ(3) USING "startTime" AT TIME ZONE 'UTC',
ALTER COLUMN "briefingPublishedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "briefingPublishedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "discordPublishedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "discordPublishedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventActivity" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventParticipant" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "cancelledAt" SET DATA TYPE TIMESTAMPTZ(3) USING "cancelledAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventPositionApplication" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventTemplate" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventTemplateVisibilityRole" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EventVisibilityRole" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Flow" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "GameVersion" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "dataUpdatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "dataUpdatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "LogAnalyzerEntry" ALTER COLUMN "eventAt" SET DATA TYPE TIMESTAMPTZ(3) USING "eventAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "NotificationSetting" ALTER COLUMN "disabledAt" SET DATA TYPE TIMESTAMPTZ(3) USING "disabledAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OnSiteNotification" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "readAt" SET DATA TYPE TIMESTAMPTZ(3) USING "readAt" AT TIME ZONE 'UTC',
ALTER COLUMN "archivedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "archivedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OnboardingStepProgress" ALTER COLUMN "completedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "completedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OnboardingTaskProgress" ALTER COLUMN "completedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "completedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Organization" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OrganizationAttributeHistoryEntry" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "confirmedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "confirmedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OrganizationMembershipHistoryEntry" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "confirmedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "confirmedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "PenaltyEntry" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "ProfitDistributionCycle" ALTER COLUMN "collectionEndsAt" SET DATA TYPE TIMESTAMPTZ(3) USING "collectionEndsAt" AT TIME ZONE 'UTC',
ALTER COLUMN "payoutStartedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "payoutStartedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "payoutEndsAt" SET DATA TYPE TIMESTAMPTZ(3) USING "payoutEndsAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "collectionEndedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "collectionEndedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "payoutEndedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "payoutEndedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "ProfitDistributionCycleParticipant" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "cededAt" SET DATA TYPE TIMESTAMPTZ(3) USING "cededAt" AT TIME ZONE 'UTC',
ALTER COLUMN "acceptedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "acceptedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "disbursedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "disbursedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "ReadMarker" ALTER COLUMN "readAt" SET DATA TYPE TIMESTAMPTZ(3) USING "readAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoleAssignment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "currentLevelUpdatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "currentLevelUpdatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoleAssignmentChange" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoleAssignmentLevelChange" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "RoleCitizenCount" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "SeasonalThemeSetting" ALTER COLUMN "disabledAt" SET DATA TYPE TIMESTAMPTZ(3) USING "disabledAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMPTZ(3) USING "expires" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Ship" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "SilcSetting" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "SilcTransaction" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ(3) USING "expiresAt" AT TIME ZONE 'UTC',
ALTER COLUMN "cancelledAt" SET DATA TYPE TIMESTAMPTZ(3) USING "cancelledAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "completedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "completedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "TaskAssignment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Upload" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "emailVerified" SET DATA TYPE TIMESTAMPTZ(3) USING "emailVerified" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "lastSeenAt" SET DATA TYPE TIMESTAMPTZ(3) USING "lastSeenAt" AT TIME ZONE 'UTC',
ALTER COLUMN "bannedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "bannedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "VariantExternalLink" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "VariantShipCount" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "VariantTag" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "VerificationToken" ALTER COLUMN "expires" SET DATA TYPE TIMESTAMPTZ(3) USING "expires" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WebPushSubscription" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPage" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "deletedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageCitizenMention" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "notifiedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "notifiedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "suppressedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "suppressedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageFavorite" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageReport" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "resolvedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "resolvedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageSnapshot" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageSnapshotUpload" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageTag" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageUpload" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiPageVisit" ALTER COLUMN "lastVisitedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "lastVisitedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiSetting" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3) USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "WikiTag" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3) USING "createdAt" AT TIME ZONE 'UTC';

