services:

  psql:
    image: postgres:18.4-alpine3.23@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: no
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 5432:5432

  soketi:
    image: quay.io/soketi/soketi:1.6.1-16-distroless@sha256:22486a3b4ac387a3c7ee97963cccf5189d38c0a54b0d75f10c0881d60437a77a
    restart: no
    environment:
      SOKETI_DEFAULT_APP_USER_AUTHENTICATION: "true"
    ports:
      - 6001:6001
      - 9601:9601
