export const cornerstoneImageBrowserItemTypes = [
  {
    title: "Helme",
    page: "helmets",
    dataUrl: "https://finder.cstone.space/GetArmors/Helmets",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Arme",
    page: "arms",
    dataUrl: "https://finder.cstone.space/GetArmors/Arms",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Torso",
    page: "torsos",
    dataUrl: "https://finder.cstone.space/GetArmors/Torsos",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Rucksäcke",
    page: "backpacks",
    dataUrl: "https://finder.cstone.space/GetArmors/Backpacks",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Beine",
    page: "legs",
    dataUrl: "https://finder.cstone.space/GetArmors/Legs",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Undersuits",
    page: "undersuites",
    dataUrl: "https://finder.cstone.space/GetArmors/Undersuits",
    linkBase: "https://finder.cstone.space/FPSArmors1",
    category: "armor",
  },
  {
    title: "Hüte",
    page: "hats",
    dataUrl: "https://finder.cstone.space/GetClothes/Hat",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Brillen",
    page: "eyes",
    dataUrl: "https://finder.cstone.space/GetClothes/Eyes",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Handschuhe",
    page: "hands",
    dataUrl: "https://finder.cstone.space/GetClothes/Hands",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Jacken",
    page: "jacket",
    dataUrl: "https://finder.cstone.space/GetClothes/Jacket",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Oberteile",
    page: "shirt",
    dataUrl: "https://finder.cstone.space/GetClothes/Shirt",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Jumpsuits",
    page: "jumpsuit",
    dataUrl: "https://finder.cstone.space/GetClothes/Jumpsuit",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Hosen",
    page: "civil-legs",
    dataUrl: "https://finder.cstone.space/GetClothes/Legs",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Schuhe",
    page: "feet",
    dataUrl: "https://finder.cstone.space/GetClothes/Feet",
    linkBase: "https://finder.cstone.space/FPSClothes1",
    category: "clothing",
  },
  {
    title: "Schusswaffen",
    page: "ranged",
    dataUrl: "https://finder.cstone.space/GetFPSWeapons",
    linkBase: "https://finder.cstone.space/FPSWeapons1",
    category: "weapons",
  },
  {
    title: "Messer",
    page: "knives",
    dataUrl: "https://finder.cstone.space/GetFPSWeaponMelee",
    linkBase: "https://finder.cstone.space/FPSWeaponMelee1",
    category: "weapons",
  },
] as const;
