# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      # Mount node_modules into a volume to improve performance (see https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-targeted-named-volume)
      - devcontainer-node_modules:/workspace/node_modules
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:15.6-alpine3.19
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  devcontainer-node_modules:
  postgres-data:
