version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:15.6-alpine3.19
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
