import type { GenericEntityLogType } from "@/types";

export interface PermissionSet {
  resource:
    | GenericEntityLogType
    | "login"
    | "event"
    | "orgFleet"
    | "ship"
    | "manufacturersSeriesAndVariants"
    | "citizen"
    | "organization"
    | "organizationMembership"
    | "noteType"
    | "user"
    | "role"
    | "classificationLevel"
    | "analytics"
    | "lastSeen"
    | "otherRole"
    | "note"
    | "eventFleet"
    | "documentAlliance"
    | "documentOnboarding"
    | "documentA1"
    | "documentA2"
    | "documentA3"
    | "documentMember"
    | "documentRecon"
    | "documentDogfight"
    | "documentAdvancedDogfight"
    | "documentHandsOnDeck"
    | "documentEngineering"
    | "documentBootsOnTheGround"
    | "documentCaptainOnTheBridge"
    | "documentMissiles"
    | "documentBombardment"
    | "documentInterdictAndDisable"
    | "documentLeadership"
    | "documentTechAndTactic"
    | "documentFrontline"
    | "documentLeadThePack"
    | "documentSupervisor"
    | "documentManager"
    | "documentSalvage"
    | "documentMining"
    | "documentTradeAndTransport"
    | "documentScavenger"
    | "documentMarketeer"
    | "documentPolaris"
    | "algolia"
    | "spynetActivity"
    | "spynetCitizen"
    | "spynetNotes"
    | "spynetOther"
    | "career"
    | "leaderboards"
    | "penaltyEntry"
    | "ownPenaltyEntry"
    | "othersEventPosition"
    | "silcBalanceOfOtherCitizen"
    | "silcBalanceOfCurrentCitizen"
    | "silcTransactionOfOtherCitizen"
    | "silcTransactionOfCurrentCitizen"
    | "silcSetting"
    | "task"
    | "logAnalyzer"
    | "profitDistributionCycle"
    | "globalStatistics"
    | "systemLog";
  operation:
    | "create"
    | "read"
    | "readRedacted"
    | "update"
    | "delete"
    | "manage"
    | "confirm"
    | "assign"
    | "dismiss"
    | "negate";
  attributes?: PermissionSetAttribute[];
}

export interface PermissionSetAttribute {
  key:
    | "confirmed"
    | "noteTypeId"
    | "classificationLevelId"
    | "alsoUnconfirmed"
    | "roleId"
    | "alsoVisibilityRedacted"
    | "flowId"
    | "taskVisibility"
    | "taskRewardType"
    | "taskDeleted";
  value: string | boolean;
}
