name: Build Lambda functions (pnpm)

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.git_ref }}

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 11.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: "pnpm-monorepo/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "pnpm-monorepo/pnpm-lock.yaml"

      - name: pnpm audit guard
        run: pnpm audit
        working-directory: pnpm-monorepo

      - name: Install dependencies
        run: pnpm install
        working-directory: pnpm-monorepo

      - name: Build
        run: pnpm run build:lambda
        working-directory: pnpm-monorepo

      - name: Store artifact (midnight-automations)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: midnight-automations-dist
          path: pnpm-monorepo/apps/lambda/build/midnight-automations.zip
          retention-days: 1

      - name: Store artifact (frequent-automations)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: frequent-automations-dist
          path: pnpm-monorepo/apps/lambda/build/frequent-automations.zip
          retention-days: 1

      - name: Store artifact (notification-router)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: notification-router-dist
          path: pnpm-monorepo/apps/lambda/build/notification-router.zip
          retention-days: 1

      - run: mv pnpm-monorepo/apps/lambda/build/scrape-discord-events.zip pnpm-monorepo/apps/lambda/build/scrape-discord-events-function.zip
      - name: Store artifact (scrape-discord-events)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: scrape-discord-events-function-dist
          path: pnpm-monorepo/apps/lambda/build/scrape-discord-events-function.zip
          retention-days: 1

      - name: Store artifact (email-function)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: email-function-dist
          path: pnpm-monorepo/apps/lambda/build/email-function.zip
          retention-days: 1
