name: Build email-functon

on:
  workflow_call:

jobs:
  plan:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: 1.0.26

      - uses: actions/cache@v4.0.0
        id: emails-node-modules-cache
        with:
          path: emails/node_modules
          key: ${{ runner.os }}-${{ hashFiles('emails/bun.lockb') }}

      - name: Install dependencies of emails
        run: bun install --frozen-lockfile
        working-directory: emails
        if: steps.emails-node-modules-cache.outputs.cache-hit != 'true'

      - uses: actions/cache@v4.0.0
        id: email-function-node-modules-cache
        with:
          path: email-function/node_modules
          key: ${{ runner.os }}-${{ hashFiles('email-function/bun.lockb') }}

      - name: Install dependencies of email-function
        run: bun install --frozen-lockfile
        working-directory: email-function
        if: steps.email-function-node-modules-cache.outputs.cache-hit != 'true'

      - name: Build email-function
        run: bun run build:lambda
        working-directory: email-function

      - name: Store email-function artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: email-function-dist
          path: email-function/dist/
          retention-days: 1
