name: Build Lambda functions

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.git_ref }}

      - uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: 1.2.4

      - uses: actions/cache@v4.2.2
        id: node-modules-cache
        with:
          path: bun-packages/node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun-packages/bun.lockb') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: bun-packages
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Build
        run: |
          SHA=$(git log -1 '--format=format:%H')
          # bun run build --define:process.env.COMMIT_SHA=\\\"$SHA\\\"
          bun run build
        working-directory: bun-packages/packages/email-function

      - name: Build
        run: |
          SHA=$(git log -1 '--format=format:%H')
          # bun run build --define:process.env.COMMIT_SHA=\\\"$SHA\\\"
          bun run build
        working-directory: bun-packages/packages/scrape-discord-events-function

      - name: Store artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: email-function-dist
          path: bun-packages/packages/email-function/dist/
          retention-days: 1

      - name: Store artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: scrape-discord-events-function-dist
          path: bun-packages/packages/scrape-discord-events-function/dist/
          retention-days: 1
          include-hidden-files: true # Required for the .prisma folder within node_modules
