name: Build email-functon

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string

jobs:
  build-email-function:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.3
        with:
          ref: ${{ inputs.git_ref }}

      - uses: oven-sh/setup-bun@v1.2.1
        with:
          bun-version: 1.1.8

      - uses: actions/cache@v4.0.2
        id: node-modules-cache
        with:
          path: bun-packages/node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun-packages/bun.lockb') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: bun-packages
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Build
        run: |
          SHA=git log -1 '--format=format:%H'
          bun run build --define:process.env.COMMIT_SHA=\\\"$SHA\\\"
        working-directory: bun-packages/packages/email-function

      - name: Store artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: email-function-dist
          path: bun-packages/packages/email-function/dist/
          retention-days: 1
