name: Production database migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    environment: Production

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.20.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "pnpm-monorepo/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "pnpm-monorepo/pnpm-lock.yaml"

      - name: pnpm audit guard
        run: pnpm audit
        working-directory: pnpm-monorepo

      - name: Install dependencies
        run: pnpm install --filter @sam-monorepo/database
        working-directory: pnpm-monorepo

      - name: Run database migrations
        run: pnpm exec prisma migrate deploy
        working-directory: pnpm-monorepo/packages/database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
