name: Production database migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    environment: Production

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "app/.nvmrc"

      - name: npm audit guard
        run: npm audit
        working-directory: app

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Run database migrations
        run: npx prisma migrate deploy
        working-directory: app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
