name: Production deployment

on:
  # schedule:
  #   - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-22.04

    # Related
    # - https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # - https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
    permissions:
      # Required for actions/github-script
      #
      # Also enable "Allow GitHub Actions to create and approve pull requests" in Settings/Actions/General/Workflow permissions
      pull-requests: write

    steps:
      - uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Related:
          # - https://octokit.github.io/rest.js
          # - https://docs.github.com/en/rest/pulls/pulls
          script: |
            const existingPullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "develop",
              base: "main",
              state: "open",
            })

            if (existingPullRequests.data.length > 0) {
              console.info("Pull Request already exists")
              return
            }

            try {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: "develop",
                base: "main",
                title: `Production deployment (${new Date().toISOString()})`,
              })
            } catch (error) {
              console.log(error.response.data.errors[0].message)
              console.log(error.response.data.errors[0].message === "No commits between develop and main")
              // throw error
            }
