name: Renovate

on:
  schedule:
    - cron: "30 2 * * 1" # Every Monday at 2:30 AM UTC
    - cron: "30 3 * * 1" # Every Monday at 3:00 AM UTC (wait for workflows in Pull Requests to finish)
  workflow_dispatch: # Manually run the workflow
  push: # Run the workflow on changes to the configuration
    branches:
      - develop
    paths:
      - renovate.json
      - .github/workflows/renovate.yml

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
