name: Renovate

on:
  schedule:
    - cron: "0,30 3,4,5 * * *" # Every day six chances for Renovate to create or rebase branches and create, rebase or merge PRs
  workflow_dispatch: # Manually run the workflow
  push: # Run the workflow on changes to the configuration
    branches:
      - develop
    paths:
      - renovate.json
      - .github/workflows/renovate.yml

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
