name: Renovate

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch: # Manually run the workflow
  push: # Run the workflow on changes to the configuration
    branches:
      - develop
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
      - .github/renovate-config.js

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
