name: Renovate

on:
  schedule:
    - cron: "0,30 6 * * *" # Every day twice in order to raise and merge PRs for security patches
  workflow_dispatch: # Manually run the workflow
  push: # Run the workflow on changes to the configuration
    branches:
      - develop
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
      - .github/renovate-config.js

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
