name: terraform validate

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/terraform-validate.yml
      - terraform/**
  push:
    branches:
      - develop
    paths:
      - .github/workflows/terraform-validate.yml
      - terraform/**

jobs:
  validate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Read .terraform-version
        id: terraform_version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_version: "${{ steps.terraform_version.outputs.value }}"

      - name: terraform init
        run: terraform init -backend=false
        working-directory: terraform

      - name: terraform validate
        run: terraform validate
        working-directory: terraform
