name: terraform plan

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_email_function:
    uses: ./.github/workflows/build-email-function.yml

  plan:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    needs: [build_email_function]

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::220746603587:role/github-actions
          aws-region: eu-central-1

      - name: Retrieve email-function artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: email-function-dist
          path: email-function/dist

      - name: terraform init
        run: terraform init -backend-config=test.s3.tfbackend
        working-directory: terraform

      - name: terraform plan
        run: terraform plan
        working-directory: terraform
