name: terraform validate

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/terraform-validate.yml
      - terraform/**

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Read .terraform-version
        id: terraform_version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: "${{ steps.terraform_version.outputs.value }}"

      - name: terraform init
        run: terraform init -backend=false
        working-directory: terraform

      - name: terraform validate
        run: terraform validate
        working-directory: terraform
