name: terraform validate

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - terraform/**

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.6.4

      - name: terraform init
        run: terraform init -backend=false
        working-directory: terraform

      - name: terraform validate
        run: terraform validate
        working-directory: terraform
