name: Validate app

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/validate-app.yml
      - app/**
  push:
    branches:
      - develop
    paths:
      - .github/workflows/validate-app.yml
      - app/**

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: "app/.nvmrc"

      - name: npm audit guard
        run: npm audit
        working-directory: app

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Lint
        run: npm run lint
        working-directory: app
        continue-on-error: true
        env:
          SKIP_VALIDATION: "1"

  prettier:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: "app/.nvmrc"

      - name: npm audit guard
        run: npm audit
        working-directory: app

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Prettier
        run: npx prettier --check .
        working-directory: app

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: "app/.nvmrc"

      - name: npm audit guard
        run: npm audit
        working-directory: app

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Test
        run: npm run test
        working-directory: app
