name: Validate email-function

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/validate-email-function.yml
      - bun-packages/packages/email-function/**
      - bun-packages/biome.json
  push:
    branches:
      - develop

jobs:
  biome:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set up Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.5.3

      - name: Run Biome
        run: biome ci .
        working-directory: bun-packages/packages/email-function
