name: Validate app

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/validate-app.yml
      - app/**

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          package_json_file: "app/package.json"

      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: "app/.nvmrc"
          cache: 'pnpm'
          cache-dependency-path: 'app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: app

      - name: Lint
        run: pnpm run lint
        working-directory: app
        continue-on-error: true
        env:
          SKIP_VALIDATION: "1"

  prettier:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          package_json_file: "app/package.json"

      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: "app/.nvmrc"
          cache: 'pnpm'
          cache-dependency-path: 'app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: app

      - name: Prettier
        run: pnpm exec prettier --check .
        working-directory: app
        continue-on-error: true

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          package_json_file: "app/package.json"

      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: "app/.nvmrc"
          cache: 'pnpm'
          cache-dependency-path: 'app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: app

      - name: Test
        run: pnpm run test
        working-directory: app
