name: Validate app

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/validate-app.yml
      - app/**
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version-file: "app/.nvmrc"

      - uses: actions/cache@v4.3.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        env:
          SKIP_VALIDATION: "1"

      - name: Lint
        run: npm run lint
        working-directory: app
        continue-on-error: true
        env:
          SKIP_VALIDATION: "1"

  prettier:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version-file: "app/.nvmrc"

      - uses: actions/cache@v4.3.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        env:
          SKIP_VALIDATION: "1"

      - name: Prettier
        run: npx prettier --check .
        working-directory: app
        continue-on-error: true

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version-file: "app/.nvmrc"

      - uses: actions/cache@v4.3.0
        id: node-modules-cache
        with:
          path: app/node_modules
          key: ${{ runner.os }}-${{ hashFiles('app/.nvmrc', 'app/package-lock.json', 'app/prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci
        working-directory: app
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        env:
          SKIP_VALIDATION: "1"

      - name: Test
        run: npm run test
        working-directory: app
